#!/bin/sh
# fluxbox-ts
# ----------
# Fluxbox Theme Save (style, init, apps, gtk theme, icon, and wallpaper)

user=`whoami`
style=`grep session.styleFile /home/$user/.fluxbox/init | awk -F/ '{print $6}'`
mkdir /home/$user/.fluxbox/themes/$style
cp /home/$user/.fluxbox/init /home/$user/.fluxbox/themes/$style/init
cp /home/$user/.fluxbox/apps /home/$user/.fluxbox/themes/$style/apps
cp /home/$user/.gtkrc-2.0 /home/$user/.fluxbox/themes/$style/.gtkrc-2.0
cp /home/$user/.config/gtk-3.0/settings.ini /home/$user/.fluxbox/themes/$style/settings.ini
cp /home/$user/.fehbg /home/$user/.fluxbox/themes/$style/.fehbg
cat > /home/$user/.fluxbox/themes/$style/$style <<++
#!/bin/sh
cp /home/$user/.fluxbox/themes/$style/init /home/$user/.fluxbox/init
cp /home/$user/.fluxbox/themes/$style/apps /home/$user/.fluxbox/apps
cp /home/$user/.fluxbox/themes/$style/.gtkrc-2.0 /home/$user/.gtkrc-2.0
cp /home/$user/.fluxbox/themes/$style/settings.ini /home/$user/.config/gtk-3.0/settings.ini
cp /home/$user/.fluxbox/themes/$style/.fehbg /home/$user/.fehbg
++
chmod +x /home/$user/.fluxbox/themes/$style/$style
